movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .form import movieform
from .models import movie

# Create your views here.
def index(request):

    Movie= movie.objects.all()
    context={
        'movie_list':Movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    Movie=movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':Movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        Movie= movie(name=name,desc=desc,year=year,img=img)
        Movie.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    Movie=movie.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES or None,instance=Movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':Movie})

def delete(request,id):
    if request.method=="POST":
        Movie=movie.objects.get(id=id)
        Movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST", enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter Movie Name"><br><br>
  <input type="text" name="desc" placeholder="Enter Movie Desc"><br><br>
  <input type="text" name="year" placeholder="Enter Movie Year"><br><br>
  <input type="file" name="img"><br><br>
  <input type="submit">

</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
     ONLINE MOVIE STORE

<a href="{% url 'movieapp:add_movie' %}" class="btn btn-success">Add Movie</a>


  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Are you wamt to delete this movie?
  <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="350", height="345">
            <div class="col-md-6">
                <h4><b>{{movie.name}}</b></h4>
                <h6>{{movie.desc}}</h6>
                <h6>{{movie.year}}</h6>
                <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
                <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3 m-4">
            <div class="card h-100" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap"  style="width: 283px; height: 280px;">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}.</p>
    <a href="{% url  'movieapp:detail' i.id %}" class="btn btn-primary">Details</a>



  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}